name: Create Tag, Release, and Build on Main Push

on:
  workflow_dispatch:

permissions:
  contents: write
jobs:
  tag_release_build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: "${{ secrets.DEPLOY_KEY }}"

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.DEPLOY_KEY }}
          tag_prefix: "v"
          default_bump: "patch"

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          generate_release_notes: true
          prerelease: false
          token: ${{ secrets.DEPLOY_KEY }}
